version: '3.8'

services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hulkstore

  hulkstore:
    build: .
    container_name: hulkstore
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/hulkstore